import Link from 'next/link';

export default function TermsOfService() {
  return (
    <main className="min-h-screen bg-paper py-12 md:py-24 px-4">
      <div className="max-w-4xl mx-auto">
        <Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-muted hover:text-ink transition-colors mb-12 group">
          <svg width="16" height="16" viewBox="0 0 16 16" fill="none" className="group-hover:-translate-x-1 transition-transform">
            <path d="M10 12L6 8L10 4" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
          </svg>
          Back to Studio
        </Link>

        <header className="mb-16">
          <h1 className="text-4xl md:text-5xl font-bold font-display text-ink mb-4">Terms of Service</h1>
          <p className="text-muted font-medium">Effective Date: April 2026</p>
        </header>

        <div className="prose prose-slate max-w-none space-y-8 text-muted leading-relaxed">
          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-ink font-display">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Fish Audio Online, you agree to be bound by these Terms of Service. If you do not agree to all of these terms, do not use the service.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-ink font-display">2. Description of Service</h2>
            <p>
              Fish Audio Online provides a web-based Text-to-Speech (TTS) generation service. We offer high-quality AI voices for personal and commercial use without requiring registration or fees.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-ink font-display">3. Commercial License & Usage</h2>
            <p>
              <strong>Full Rights:</strong> Users are granted a non-exclusive, worldwide, perpetual license to use the audio generated by Fish Audio Online for any legal purpose, including commercial YouTube videos, podcasts, and social media content.
            </p>
            <p>
              <strong>No Attribution:</strong> You are not required to provide credit or attribution to Fish Audio Online, although we appreciate it.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-ink font-display">4. User Conduct & Restrictions</h2>
            <p>
              You agree not to use the service for:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Generating illegal, hateful, or harmful content.</li>
              <li>Impersonating individuals without their consent.</li>
              <li>Automated scraping or abusive API requests that degrade service performance.</li>
              <li>Bypassing or attempting to bypass our security or ad-delivery systems.</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-ink font-display">5. Advertisements</h2>
            <p>
              To provide this service for free, Fish Audio Online displays advertisements. By using the service, you consent to the delivery of these advertisements. Attempting to bypass these ads through scripts or automated means is a violation of these terms.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-ink font-display">6. Disclaimer of Warranties</h2>
            <p>
              The service is provided &quot;as is&quot; and &quot;as available&quot; without any warranties of any kind. We do not guarantee that the service will be uninterrupted or error-free.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-ink font-display">7. Limitation of Liability</h2>
            <p>
              In no event shall Fish Audio Online be liable for any indirect, incidental, or consequential damages arising out of your use of the service.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-ink font-display">8. Termination</h2>
            <p>
              We reserve the right to block access to the service for users who violate these terms or engage in abusive behavior.
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
